# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Niraali Patel\Documents\VOC\Group 3 - House Price Predictor\GUI\Explorer.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1918, 1027)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        mainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileSelector = QtWidgets.QPushButton(self.centralwidget)
        self.fileSelector.setGeometry(QtCore.QRect(20, 30, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.fileSelector.setFont(font)
        self.fileSelector.setStyleSheet("background-color: rgb(255, 198, 181);")
        self.fileSelector.setObjectName("fileSelector")
        self.enterButton = QtWidgets.QPushButton(self.centralwidget)
        self.enterButton.setGeometry(QtCore.QRect(20, 370, 210, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 198, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enterButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.enterButton.setFont(font)
        self.enterButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.enterButton.setStyleSheet("background-color: rgb(255, 198, 181);")
        self.enterButton.setObjectName("enterButton")
        self.countyDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.countyDropDown.setGeometry(QtCore.QRect(20, 130, 210, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.countyDropDown.setFont(font)
        self.countyDropDown.setStyleSheet("background-color: rgb(255, 198, 181);")
        self.countyDropDown.setEditable(False)
        self.countyDropDown.setCurrentText("")
        self.countyDropDown.setObjectName("countyDropDown")
        self.countyDropDown.addItem("")
        self.countyDropDown.setItemText(0, "")
        self.countyDropDown.addItem("")
        self.houseNoInput = QtWidgets.QLineEdit(self.centralwidget)
        self.houseNoInput.setGeometry(QtCore.QRect(20, 210, 210, 30))
        self.houseNoInput.setObjectName("houseNoInput")
        self.postcodeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.postcodeInput.setGeometry(QtCore.QRect(20, 325, 210, 30))
        self.postcodeInput.setObjectName("postcodeInput")
        self.houseNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.houseNoLabel.setGeometry(QtCore.QRect(20, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.houseNoLabel.setFont(font)
        self.houseNoLabel.setObjectName("houseNoLabel")
        self.postcodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.postcodeLabel.setGeometry(QtCore.QRect(20, 240, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.postcodeLabel.setFont(font)
        self.postcodeLabel.setObjectName("postcodeLabel")
        self.countyLabel = QtWidgets.QLabel(self.centralwidget)
        self.countyLabel.setGeometry(QtCore.QRect(20, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.countyLabel.setFont(font)
        self.countyLabel.setObjectName("countyLabel")
        self.tableViewer = QtWidgets.QTableView(self.centralwidget)
        self.tableViewer.setGeometry(QtCore.QRect(280, 61, 1551, 381))
        self.tableViewer.setObjectName("tableViewer")
        self.ashfieldCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ashfieldCheck.setGeometry(QtCore.QRect(30, 540, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ashfieldCheck.setFont(font)
        self.ashfieldCheck.setObjectName("ashfieldCheck")
        self.bassetlawCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.bassetlawCheck.setGeometry(QtCore.QRect(30, 570, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bassetlawCheck.setFont(font)
        self.bassetlawCheck.setObjectName("bassetlawCheck")
        self.gedlingCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.gedlingCheck.setGeometry(QtCore.QRect(30, 630, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gedlingCheck.setFont(font)
        self.gedlingCheck.setObjectName("gedlingCheck")
        self.mansfieldCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.mansfieldCheck.setGeometry(QtCore.QRect(30, 660, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mansfieldCheck.setFont(font)
        self.mansfieldCheck.setObjectName("mansfieldCheck")
        self.newarkCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.newarkCheck.setGeometry(QtCore.QRect(30, 690, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.newarkCheck.setFont(font)
        self.newarkCheck.setObjectName("newarkCheck")
        self.nottinghamCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.nottinghamCheck.setGeometry(QtCore.QRect(30, 720, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nottinghamCheck.setFont(font)
        self.nottinghamCheck.setObjectName("nottinghamCheck")
        self.rushcliffeCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.rushcliffeCheck.setGeometry(QtCore.QRect(30, 750, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rushcliffeCheck.setFont(font)
        self.rushcliffeCheck.setObjectName("rushcliffeCheck")
        self.broxtoweCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.broxtoweCheck.setGeometry(QtCore.QRect(30, 600, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.broxtoweCheck.setFont(font)
        self.broxtoweCheck.setObjectName("broxtoweCheck")
        self.enterButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.enterButton2.setGeometry(QtCore.QRect(20, 810, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.enterButton2.setFont(font)
        self.enterButton2.setStyleSheet("background-color: rgb(255, 198, 181);")
        self.enterButton2.setObjectName("enterButton2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 460, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 500, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1090, 500, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(810, 10, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.mplDistrict = MplWidget(self.centralwidget)
        self.mplDistrict.setGeometry(QtCore.QRect(290, 530, 750, 420))
        self.mplDistrict.setObjectName("mplDistrict")
        self.label_8 = QtWidgets.QLabel(self.mplDistrict)
        self.label_8.setGeometry(QtCore.QRect(0, 170, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.mplDistrict)
        self.label_9.setGeometry(QtCore.QRect(360, 390, 61, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.mplSpecific = MplWidget(self.centralwidget)
        self.mplSpecific.setGeometry(QtCore.QRect(1080, 530, 750, 420))
        self.mplSpecific.setObjectName("mplSpecific")
        self.label_7 = QtWidgets.QLabel(self.mplSpecific)
        self.label_7.setGeometry(QtCore.QRect(360, 390, 61, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.mplSpecific)
        self.label_6.setGeometry(QtCore.QRect(0, 170, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.predictionPrototypeButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictionPrototypeButton.setGeometry(QtCore.QRect(20, 880, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.predictionPrototypeButton.setFont(font)
        self.predictionPrototypeButton.setStyleSheet("background-color: rgb(255, 198, 181);")
        self.predictionPrototypeButton.setObjectName("predictionPrototypeButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 265, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.fileSelector, self.countyDropDown)
        mainWindow.setTabOrder(self.countyDropDown, self.houseNoInput)
        mainWindow.setTabOrder(self.houseNoInput, self.postcodeInput)
        mainWindow.setTabOrder(self.postcodeInput, self.enterButton)
        mainWindow.setTabOrder(self.enterButton, self.ashfieldCheck)
        mainWindow.setTabOrder(self.ashfieldCheck, self.bassetlawCheck)
        mainWindow.setTabOrder(self.bassetlawCheck, self.broxtoweCheck)
        mainWindow.setTabOrder(self.broxtoweCheck, self.gedlingCheck)
        mainWindow.setTabOrder(self.gedlingCheck, self.mansfieldCheck)
        mainWindow.setTabOrder(self.mansfieldCheck, self.newarkCheck)
        mainWindow.setTabOrder(self.newarkCheck, self.nottinghamCheck)
        mainWindow.setTabOrder(self.nottinghamCheck, self.rushcliffeCheck)
        mainWindow.setTabOrder(self.rushcliffeCheck, self.enterButton2)
        mainWindow.setTabOrder(self.enterButton2, self.predictionPrototypeButton)
        mainWindow.setTabOrder(self.predictionPrototypeButton, self.tableViewer)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Data Exploration"))
        self.fileSelector.setText(_translate("mainWindow", "Choose File"))
        self.enterButton.setText(_translate("mainWindow", "Enter"))
        self.countyDropDown.setItemText(1, _translate("mainWindow", "NOTTINGHAMSHIRE"))
        self.houseNoLabel.setText(_translate("mainWindow", "House Number"))
        self.postcodeLabel.setText(_translate("mainWindow", "Postcode"))
        self.countyLabel.setText(_translate("mainWindow", "County"))
        self.ashfieldCheck.setText(_translate("mainWindow", "Ashfield"))
        self.bassetlawCheck.setText(_translate("mainWindow", "Bassetlaw"))
        self.gedlingCheck.setText(_translate("mainWindow", "Gedling"))
        self.mansfieldCheck.setText(_translate("mainWindow", "Mansfield"))
        self.newarkCheck.setText(_translate("mainWindow", "Newark and Sherwood"))
        self.nottinghamCheck.setText(_translate("mainWindow", "Nottingham"))
        self.rushcliffeCheck.setText(_translate("mainWindow", "Rushcliffe"))
        self.broxtoweCheck.setText(_translate("mainWindow", "Broxtowe"))
        self.enterButton2.setText(_translate("mainWindow", "Enter"))
        self.label.setText(_translate("mainWindow", "Average Prices for Each District"))
        self.label_2.setText(_translate("mainWindow", "Bar Chart Showing Selected Average Prices"))
        self.label_4.setText(_translate("mainWindow", "Price Paid Data for Houses/Areas"))
        self.label_8.setText(_translate("mainWindow", "Avg \n"
"Price\n"
"(£\'s)"))
        self.label_9.setText(_translate("mainWindow", "District"))
        self.label_7.setText(_translate("mainWindow", "Year"))
        self.label_6.setText(_translate("mainWindow", "Price\n"
"(£\'s)"))
        self.predictionPrototypeButton.setText(_translate("mainWindow", "Prediction Prototype \n"
" Window"))
        self.label_5.setText(_translate("mainWindow", "(Input any length postcode \n"
"including a space)"))


from GUI.models.mplwidget import MplWidget
