# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Niraali Patel\Documents\VOC\Group 3 - House Price Predictor\GUI\Explorer.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1819, 1027)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileSelector = QtWidgets.QPushButton(self.centralwidget)
        self.fileSelector.setGeometry(QtCore.QRect(20, 60, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.fileSelector.setFont(font)
        self.fileSelector.setObjectName("fileSelector")
        self.enterButton = QtWidgets.QPushButton(self.centralwidget)
        self.enterButton.setGeometry(QtCore.QRect(20, 380, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.enterButton.setFont(font)
        self.enterButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.enterButton.setObjectName("enterButton")
        self.countyDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.countyDropDown.setGeometry(QtCore.QRect(20, 160, 211, 31))
        self.countyDropDown.setEditable(False)
        self.countyDropDown.setCurrentText("")
        self.countyDropDown.setObjectName("countyDropDown")
        self.countyDropDown.addItem("")
        self.countyDropDown.setItemText(0, "")
        self.countyDropDown.addItem("")
        self.houseNoInput = QtWidgets.QLineEdit(self.centralwidget)
        self.houseNoInput.setGeometry(QtCore.QRect(20, 250, 211, 25))
        self.houseNoInput.setObjectName("houseNoInput")
        self.postcodeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.postcodeInput.setGeometry(QtCore.QRect(20, 330, 211, 25))
        self.postcodeInput.setObjectName("postcodeInput")
        self.houseNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.houseNoLabel.setGeometry(QtCore.QRect(20, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.houseNoLabel.setFont(font)
        self.houseNoLabel.setObjectName("houseNoLabel")
        self.postcodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.postcodeLabel.setGeometry(QtCore.QRect(20, 290, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.postcodeLabel.setFont(font)
        self.postcodeLabel.setObjectName("postcodeLabel")
        self.countyLabel = QtWidgets.QLabel(self.centralwidget)
        self.countyLabel.setGeometry(QtCore.QRect(20, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.countyLabel.setFont(font)
        self.countyLabel.setObjectName("countyLabel")
        self.tableViewer = QtWidgets.QTableView(self.centralwidget)
        self.tableViewer.setGeometry(QtCore.QRect(280, 61, 1481, 381))
        self.tableViewer.setObjectName("tableViewer")
        self.ashfieldCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ashfieldCheck.setGeometry(QtCore.QRect(40, 540, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ashfieldCheck.setFont(font)
        self.ashfieldCheck.setObjectName("ashfieldCheck")
        self.bassetlawCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.bassetlawCheck.setGeometry(QtCore.QRect(40, 580, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bassetlawCheck.setFont(font)
        self.bassetlawCheck.setObjectName("bassetlawCheck")
        self.gedlingCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.gedlingCheck.setGeometry(QtCore.QRect(40, 660, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gedlingCheck.setFont(font)
        self.gedlingCheck.setObjectName("gedlingCheck")
        self.mansfieldCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.mansfieldCheck.setGeometry(QtCore.QRect(40, 700, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mansfieldCheck.setFont(font)
        self.mansfieldCheck.setObjectName("mansfieldCheck")
        self.newarkCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.newarkCheck.setGeometry(QtCore.QRect(40, 740, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.newarkCheck.setFont(font)
        self.newarkCheck.setObjectName("newarkCheck")
        self.nottinghamCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.nottinghamCheck.setGeometry(QtCore.QRect(40, 780, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nottinghamCheck.setFont(font)
        self.nottinghamCheck.setObjectName("nottinghamCheck")
        self.rushcliffeCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.rushcliffeCheck.setGeometry(QtCore.QRect(40, 820, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rushcliffeCheck.setFont(font)
        self.rushcliffeCheck.setObjectName("rushcliffeCheck")
        self.broxtoweCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.broxtoweCheck.setGeometry(QtCore.QRect(40, 620, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.broxtoweCheck.setFont(font)
        self.broxtoweCheck.setObjectName("broxtoweCheck")
        self.enterButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.enterButton2.setGeometry(QtCore.QRect(20, 870, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.enterButton2.setFont(font)
        self.enterButton2.setObjectName("enterButton2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 470, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphViewer = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphViewer.setGeometry(QtCore.QRect(280, 560, 751, 371))
        self.graphViewer.setObjectName("graphViewer")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(1050, 560, 711, 371))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 518, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1300, 518, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.predictionPrototypeButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictionPrototypeButton.setGeometry(QtCore.QRect(1420, 950, 301, 61))
        self.predictionPrototypeButton.setObjectName("predictionPrototypeButton")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.fileSelector.setText(_translate("mainWindow", "Choose File"))
        self.enterButton.setText(_translate("mainWindow", "Enter"))
        self.countyDropDown.setItemText(1, _translate("mainWindow", "NOTTINGHAMSHIRE"))
        self.houseNoLabel.setText(_translate("mainWindow", "House Number"))
        self.postcodeLabel.setText(_translate("mainWindow", "Postcode (eg. \"NG9 2EL\")"))
        self.countyLabel.setText(_translate("mainWindow", "County"))
        self.ashfieldCheck.setText(_translate("mainWindow", "Ashfield"))
        self.bassetlawCheck.setText(_translate("mainWindow", "Bassetlaw"))
        self.gedlingCheck.setText(_translate("mainWindow", "Gedling"))
        self.mansfieldCheck.setText(_translate("mainWindow", "Mansfield"))
        self.newarkCheck.setText(_translate("mainWindow", "Newark and Sherwood"))
        self.nottinghamCheck.setText(_translate("mainWindow", "Nottingham"))
        self.rushcliffeCheck.setText(_translate("mainWindow", "Rushcliffe"))
        self.broxtoweCheck.setText(_translate("mainWindow", "Broxtowe"))
        self.enterButton2.setText(_translate("mainWindow", "Enter"))
        self.label.setText(_translate("mainWindow", "Average Prices for Each District"))
        self.label_2.setText(_translate("mainWindow", "Bar Chart Showing Selected Average Prices"))
        self.label_3.setText(_translate("mainWindow", "Price Change for Specific House"))
        self.label_4.setText(_translate("mainWindow", "Price Paid Data for Houses/Areas"))
        self.predictionPrototypeButton.setText(_translate("mainWindow", "Prediction Prototype"))


